### ISSUE TITLE
无法通过rpc调用进行广播

### ISSUE THREAD

**Issue by wikeex** [palletone/go-palletone#22]
我们在开发过程中发现调用wallet_sendRawTransaction rpc方法和wallet_sendRlpTransaction方法都无法广播交易，错误码：32021: borad transaction had be changed. 在全节点上手动调用这两个方法都可以成功广播。这个问题在测试网络和主网都存在。请问该如何解决这个问题？

**Comment by studyzy** [comment]
请使用最新版1.0.8，经过测试没有这个问题。
